# Generated by Django 4.1.5 on 2023-01-07 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.TextField(validators=[django.core.validators.RegexValidator(code='invalid', message='No', regex='^[a-z]+$')]),
        ),
    ]
